name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ“– Documentation'
    label: 'docs'
  - title: 'ğŸ§ª Tests'
    label: 
      - 'test'
      - 'tests'
  - title: 'â™»ï¸ Refactoring'
    label: 'refactor'
  - title: 'ğŸ’„ Styling'
    label: 'style'
  - title: 'ğŸ”„ CI/CD'
    label: 
      - 'ci'
      - 'workflow'
  - title: 'âš¡ Performanc'
    label: 
      - 'performance'
      - 'perf'
  - title: 'ğŸ—ï¸ Build'
    label: 'build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: | 
  ## Whatâ€™s Changed
 
  $CHANGES
